## Using Configs from:- https://github.com/runevad/waveshare-esp32-s3-7inch/blob/main/waveshare-esp32-s3-7inch.yaml
## And Post#2 Here:- https://community.home-assistant.io/t/waveshare-esp32-s3-touch-lcd-7/789584/2
##### IP Reservation:-192.168.59.191 #####

substitutions: 
  name: waveshare-1
  devicename: Waveshare-1
  friendly_name: Waveshare LCD-1
  id_prefix: Ws1_
  device_sampling_time: 30s

packages:
  display: !include "packages/WaveShare/Display-mipi_rgb.yaml"
  touch: !include "packages/WaveShare/TouchScreen.yaml"
  fonts: !include "packages/fonts.yaml"
  colors: !include "packages/colors.yaml"
  images: !include "img/images.yaml"
  debug: !include "packages/debug-S3.yaml"
  diag_wifi: !include "packages/diag_wifi.yaml"
  apistat: !include "packages/api_state.yaml"
  sensors_ha: !include "packages/7in_panels/sensors_ha.yaml"
  sensors_energy: !include "packages/7in_panels/sensors_energy.yaml"


# Lvgl Packages
  Styles: !include "packages/WaveShare/Lvgl-Styles.yaml"
  Themes: !include "packages/WaveShare/Lvgl-Themes.yaml"
  Top_Layer: !include "packages/WaveShare/Lvgl-Top_layer.yaml"
  Lvgl_Home: !include "packages/WaveShare/Lvgl-Main.yaml"
  Lvgl_Energy: !include "packages/WaveShare/Lvgl-Energy.yaml"
  Lvgl_BbqTV: !include "packages/WaveShare/Lvgl-BbqTv.yaml"
  Lvgl_Control: !include "packages/WaveShare/Lvgl-Control.yaml"
  Lvgl_Test: !include "packages/WaveShare/Lvgl-Test.yaml"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      
psram:
  mode: octal
  speed: 80MHz # Was 120MHz, but wouldn't Compile

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback"
    password: !secret ws1_ap_pass

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ws1_api_key
ota:
  - platform: esphome
    password: !secret ws1_ota_pass

web_server:
  version: 3
  include_internal: True

logger:
  level: DEBUG
  logs:
    touch: DEBUG
    display: DEBUG
##### I2C ###########################################################################
i2c:
  sda: GPIO08
  scl: GPIO09
  scan: True
  id: bus_a
#-------------------------------------------------------------------------------

###### IO Extender

ch422g:
  - id: ch422g_hub

##### Switches for Restart & Backlight #########################################
#-------------------------------------------------------------------------------
switch:
  - platform: restart
    name: "Restart"
    id: device_restart
  
  - platform: safe_mode
    name: Use Safe Mode
    id: device_safe_mode
    
  - platform: gpio
    id: lcdbacklight
    name: Display Backlight
    pin:
      ch422g: ch422g_hub
      number: 2
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_ON

sensor:
  - platform: homeassistant
    name: "LCD - Display Brightness"
    id: lcd_brightness
    attribute: brightness
    entity_id: light.waveshare_lcd_3_display_brightness
    internal: false
    on_value:
    - lvgl.slider.update:
        id: dimmer_slider
        value: !lambda return x;
# Extend Sensors from Packages
#sensor: 
  - id: !extend wifi_signal_db
    on_value:
      then:
        - lvgl.label.update:
            id: wf_sig
            text:
              format: "%2.0fdb"
              args: [ 'x' ]

##### Srcipt to Return to Main Page after Timeout #########################################
script:
  - id: go_home
    mode: restart # Restarts timer if called again
    then:
      - delay: 20s # Time before returning to main page
      - lvgl.page.show: main_page