sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"
#    on_value:
#      then:
#        - lvgl.label.update:
#            id: R2C3
#            text:
#              format: "%2.1f db"
#              args: [ 'x' ]
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    id: wifi_signal_pct
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""  

#----- Old Block ---------------------------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
#      name: "IP Add"
      id: ip_add

    bssid:
      name: Mac Address
      id: con_ap
      filters:
        substitute:
          - "84:D8:1B:DD:4E:F4 -> Front_Office"
          - "00:5F:67:A0:71:F0 -> Centre_Office"
          - "C0:06:C3:35:A7:FE -> Lounge_Room"
          - "00:31:92:1B:38:22 -> Bbq_Area"
          - "50:C7:BF:D3:38:5A -> Back_Room"
          - "B0:4E:26:E4:41:FE -> Outdoor"
          - "50:C7:BF:D3:3C:61 -> Shed"

  - platform: copy
    id: ip_address
    source_id: ip_add
    name: "IP Address"
  - platform: copy
    id: ap_connected
    source_id: con_ap
    name: "AP Connected"

#----- New Block --------------------------------------------------------
#text_sensor:
#  - platform: wifi_info
#    ip_address:
#      id: ip_address
##      name: "IP Add"
#
#  - platform: wifi_info
#    bssid:
#      name: Mac Address
#      id: ap_connected
#      filters:
#        substitute:
#          - "84:D8:1B:DD:4E:F4 -> Front_Office"
#          - "00:5F:67:A0:71:F0 -> Centre_Office"
#          - "C0:06:C3:35:A7:FE -> Lounge_Room"
#          - "00:31:92:1B:38:22 -> Bbq_Area"
#          - "50:C7:BF:D3:38:5A -> Back_Room"
#          - "B0:4E:26:E4:41:FE -> Outdoor"
#          - "50:C7:BF:D3:3C:61 -> Shed"
